version: '3.8'

services:
  accounts2:
    build:
      args:
        user: gseganzerla
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - accounts2

  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - 80:80
    env_file: .env
    volumes:
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - accounts2

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mariadb/dbdata:/var/lib/mysql
    networks:
      - accounts2

networks:
  accounts2:
    driver: bridge
