version: '3.8'

services:
  accounts2:
    build:
      args:
        user: gseganzerla
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - redis
      - queue
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - accounts2

  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - accounts2

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mariadb/dbdata:/var/lib/mysql
    networks:
      - accounts2

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - accounts2

  queue:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
    command: "php artisan queue:work"
    depends_on:
      - redis
    networks:
      - accounts2

networks:
  accounts2:
    driver: bridge
